package SarifMark {
    part def Program {
        doc /* Entry point and execution orchestrator. */

        comment sourceRef /* Source: src/DemaConsulting.SarifMark/Program.cs */
        comment testRef /* Test: test/DemaConsulting.SarifMark.Tests/ProgramTests.cs */
        comment designRef /* Design: docs/design/sarifmark/program.md */
        comment verificationRef /* Verification: docs/verification/sarifmark/program.md */
        comment reqRef /* Requirements: docs/reqstream/sarifmark/program.yaml */
    }
}
