---
includes:
  - docs/reqstream/sarifmark.yaml
  - docs/reqstream/sarifmark/cli.yaml
  - docs/reqstream/sarifmark/cli/context.yaml
  - docs/reqstream/sarifmark/sarif.yaml
  - docs/reqstream/sarifmark/sarif/sarif-run.yaml
  - docs/reqstream/sarifmark/sarif/sarif-finding.yaml
  - docs/reqstream/sarifmark/sarif/sarif-results.yaml
  - docs/reqstream/sarifmark/self-test.yaml
  - docs/reqstream/sarifmark/self-test/validation.yaml
  - docs/reqstream/sarifmark/utilities.yaml
  - docs/reqstream/sarifmark/utilities/path-helpers.yaml
  - docs/reqstream/sarifmark/platform-requirements.yaml
  - docs/reqstream/sarifmark/program.yaml
  - docs/reqstream/ots/xunit-v3.yaml
  - docs/reqstream/ots/reqstream.yaml
  - docs/reqstream/ots/buildmark.yaml
  - docs/reqstream/ots/versionmark.yaml
  - docs/reqstream/ots/sonarmark.yaml
  - docs/reqstream/ots/reviewmark.yaml
  - docs/reqstream/ots/pandoc.yaml
  - docs/reqstream/ots/weasyprint.yaml
  - docs/reqstream/ots/fileassert.yaml
  - docs/reqstream/ots/test-results.yaml
  - docs/reqstream/ots/sysml2tools.yaml
  - docs/reqstream/shared/sarifmark.yaml
