package SarifMark {
    part def Validation {
        doc /* Self-validation test runner. */

        comment sourceRef /* Source: src/DemaConsulting.SarifMark/SelfTest/Validation.cs */
        comment testRef /* Test: test/DemaConsulting.SarifMark.Tests/SelfTest/ValidationTests.cs */
        comment designRef /* Design: docs/design/sarifmark/self-test/validation.md */
        comment verificationRef /* Verification: docs/verification/sarifmark/self-test/validation.md */
        comment reqRef /* Requirements: docs/reqstream/sarifmark/self-test/validation.yaml */
    }
}
